### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by winds6206** [mordaha/docker-nginx-vts#1]
Hi
This project write「License MIT」 in README.md file, could you add LICENSE file into your project, choose MIT, and write your copyright. 

I will add the same  LICENSE file as yours, after your add LICENSE file.  : )

Thanks

**Comment by mordaha** [comment]
Actually i do not want any copyright, i'd like it will be public domain
Feel free to use

**Comment by winds6206** [comment]
OK, Thanks a lot.
